In [1]:
print("Hello Wold")


Hello Wold


In [2]:
student="sam"


In [3]:
student


'sam'

In [5]:
a="true"
b="false"
a

'true'

In [6]:
b

'false'

In [7]:
a==b

False

In [8]:
a!=b

True

In [11]:
a&B

False

In [12]:
B&B

False

In [13]:
a&a

True

In [14]:
student

'sam'

In [15]:
Student="Ayesha"
Student

'Ayesha'

In [16]:
type(Student)

str

In [17]:
type(a)

bool

In [18]:
a3=3.75

In [19]:
a3

3.75

In [20]:
type(a3)

float

In [21]:
a1=3+4j
a1

(3+4j)

In [22]:
type(a1)

complex

In [23]:
#This is my first Experience Of Python Programming Language



In [24]:
a=10
b=20
(a,b)

(10, 20)

In [25]:
a+b #Addition

30

In [26]:
a-b #Subtraction

-10

In [27]:
b-a

10

In [28]:
a/b #Division

0.5

In [29]:
b/a #division

2.0

In [30]:
a==b #is the value are equal or not

False

In [31]:
a>b #Greater value

False

In [32]:
b>a

True

In [33]:
a!=b

True

In [38]:
#litrals the one which cannot be changed 
#HARDCODED VALUES
STR1='This is the First String'
STR2="I AM SERVING TO PAKISTAN AIR FORCE AS A INTERNEE"
STR3="NOW,I AM LETTING TO PROFE MYSELF AS THE BEST SOFTWARE DEVELOPER OF THE HISTORY INSHALLAH"

In [39]:
STR1

'This is the First String'

In [40]:
STR2

'I AM SERVING TO PAKISTAN AIR FORCE AS A INTERNEE'

In [41]:
STR3

'NOW,I AM LETTING TO PROFE MYSELF AS THE BEST SOFTWARE DEVELOPER OF THE HISTORY INSHALLAH'

In [43]:
# EXTRACTING INDIVIDUAL CHARCATER First or last
#First
#How It Be Possible to Extract the Perticular charcater in a string.
#it is possible through by making a string variable and add square barackets.
#Inside the brackets insert a index number of any perticular char which u want to extract.
#The python index number start from '0' and including Blank spacing.
my_string="My name is Ayesha"
# Now i want to extract the 'A' of Ayesha
#Count starts From 'M'From MY.
my_string[11]

'A'

In [44]:
#Last only insert the number '-1'
my_string[-1]


'a'

In [45]:
#Extarcting sequence of characters.
#index value is inclusive to add(+1)
my_string[11:16]

'Ayesh'

In [47]:
my_string[11:-1]

'Ayesh'

In [48]:
my_string[11:15]

'Ayes'

In [49]:
my_string[11:16]

'Ayesh'

In [50]:
#WE ARE GOING TO START STRING FUNCTIONS
#fINDING THE LENGHT OF THE STRING
#len function is used
len(my_string)

17

In [51]:
len(my_string[11:-1])

5

In [53]:
my_string.lower()#converting the string letters to lowr case

'my name is ayesha'

In [55]:
#Converting String Character to Upper case
my_string.upper()

'MY NAME IS AYESHA'

In [56]:
my_string.upper([11:-1])

SyntaxError: invalid syntax (<ipython-input-56-102c344a403f>, line 1)

In [57]:
my_string.upper(my_string[11:-1])

TypeError: upper() takes no arguments (1 given)

In [58]:
#Replacing the Substring
my_string.replace('A':'W')

SyntaxError: invalid syntax (<ipython-input-58-f6ad6abd5340>, line 2)

In [59]:
my_string.replace('A','W')

'My name is Wyesha'

In [61]:
my_string.replace('a','w')

'My nwme is Ayeshw'

In [62]:
my_string.replace('Ayesha','Umer')

'My name is Umer'

In [63]:
#Number of Occurence of the substring
my_string.count("Ayesha")

1

In [64]:
#Finding Index Of substring
S1="MY NAME IS AYESHA JAVED"
S1.find('JAVED')

18

In [65]:
#sPLITTING a String 
S1.split( )

['MY', 'NAME', 'IS', 'AYESHA', 'JAVED']

In [66]:
S1.split(A)

NameError: name 'A' is not defined

In [67]:
S1.split('A')

['MY N', 'ME IS ', 'YESH', ' J', 'VED']

In [68]:
S1.lower()

'my name is ayesha javed'

In [79]:
#Concatenating the String
S2=" and i love allah"
S1+S2

'MY NAME IS AYESHA JAVED and i love allah'

# TUPLES IN PYTHON:-
#Basic Data Structure i python
#1-Tuples
#2-List
#3-Dictionary
#4-Set



#TUPLE 
# Def:-Ordered Collection of te elements which are immutable

tup1=(1,3+4j,True,"Ayesha",3.75)
tup1

In [70]:
type(tup1)

tuple

## Extarcting The Values From Tuple same like the string


#it is possible through by making a Tuple variable and add square barackets.
#Inside the brackets insert a index number of any perticular char which u want to extract.
#The python index number start from '0' and including Blank spacing.


tup1[0]

In [72]:
tup1[1]

(3+4j)

In [74]:
tup1[3]

'Ayesha'

In [75]:
#Last only insert the number '-1'

tup1[-1]

3.75

In [77]:
#Extarcting sequence of characters.
#index value is inclusive to add(+1)

tup1[3:5]

('Ayesha', 3.75)

In [78]:
#Finding Lenght of the Tuple
len(tup1)

5

In [80]:
#Concatenating Tuple
tup2=(1,"Javed",8)
tup1+tup2

(1, (3+4j), True, 'Ayesha', 3.75, 1, 'Javed', 8)

In [81]:
tup1,tup2

((1, (3+4j), True, 'Ayesha', 3.75), (1, 'Javed', 8))

In [82]:
#Repeating Tuple Element 
#Number is to be mentioned 
tup1*2

(1, (3+4j), True, 'Ayesha', 3.75, 1, (3+4j), True, 'Ayesha', 3.75)

In [83]:
#Repeating and Concatenating
tup1*2+tup2

(1,
 (3+4j),
 True,
 'Ayesha',
 3.75,
 1,
 (3+4j),
 True,
 'Ayesha',
 3.75,
 1,
 'Javed',
 8)

In [86]:
#Minimum Value and Maximum Value
tup1=(1,2,3,4,5)
tup2=(6,7,8,9,10)
min(tup1)

1

In [87]:
max(tup2)

10

In [88]:
max(tup1)

5

In [93]:
min(tup2)&max(tup1)

4

In [90]:
min(tup2)|max(tup1)

7

In [91]:
min(tup2)&min(tup1)

0

### LISTS IN PYTHON
#lists are mutable
#Hetrogeneous elements allow
#Lista are created through square Brackets '[]' while Tuples are created Through round brackets '()'





l1=[1,3+4j,True,"Ayesha",3.75]
l1

In [95]:
type(l1)

list

In [96]:
#Extracting Individual Element
l1[1]

(3+4j)

In [97]:
l1[4]

3.75

In [98]:
l1[-1]

3.75

In [99]:
l1[1:3]

[(3+4j), True]

In [100]:
l1[4:5]

[3.75]

In [101]:
l1[3:4]

['Ayesha']

In [102]:
l1[3:5]

['Ayesha', 3.75]

In [103]:
#Modifying Individual Element

#Changing the element at 0th index
l1[1]="CGPA"

In [104]:
l1

[1, 'CGPA', True, 'Ayesha', 3.75]

In [105]:
#Appending New Element 

l1.append("Excellent")
l1

[1, 'CGPA', True, 'Ayesha', 3.75, 'Excellent']

In [106]:
l1[0].append("BPGCW")

AttributeError: 'int' object has no attribute 'append'

In [107]:
#Delete (Remove) //Popping the last element
l1.pop()

'Excellent'

In [108]:
l1

[1, 'CGPA', True, 'Ayesha', 3.75]

In [109]:
#Reversing  Element of a List


l1.reverse()

In [110]:
l1

[3.75, 'Ayesha', True, 'CGPA', 1]

In [111]:
#Sorting a List 
l1.sort()
l1

TypeError: '<' not supported between instances of 'str' and 'float'

In [113]:
l1=[19,2,3.8,300.0,10,6]
l1.sort()
l1

[2, 3.8, 6, 10, 19, 300.0]

In [114]:
#Inserting Element at a specified Index

l1.insert(300.0,8)

TypeError: integer argument expected, got float

In [115]:
l1.insert(19,'ayesha')

In [116]:
l1

[2, 3.8, 6, 10, 19, 300.0, 'ayesha']

In [117]:
l1.insert(2,"Gun")

In [118]:
l1

[2, 3.8, 'Gun', 6, 10, 19, 300.0, 'ayesha']

In [119]:
l1.pop()

'ayesha'

In [120]:
l1

[2, 3.8, 'Gun', 6, 10, 19, 300.0]

In [121]:
#Reversing the list
l1.reverse()

In [122]:
l1

[300.0, 19, 10, 6, 'Gun', 3.8, 2]

In [123]:
#Concatenating the list
l1+l2[1,2,4]

NameError: name 'l2' is not defined

In [124]:
l2=[1,2,3,4]

In [125]:
l1+l2

[300.0, 19, 10, 6, 'Gun', 3.8, 2, 1, 2, 3, 4]

In [127]:
#Repeating Element
l1*2

[300.0, 19, 10, 6, 'Gun', 3.8, 2, 300.0, 19, 10, 6, 'Gun', 3.8, 2]

In [147]:
#Dictionaries in python 

#Which is the unordered collection of keyword of key_value pair

#Dictionaries are mutable(changeable)
#Starts From curly braces {}
#Hetrogenous data support

#Identicattion is so important in python 3
 d1={'Apple':50}

IndentationError: unexpected indent (<ipython-input-147-a378ca849a2f>, line 10)

In [149]:
d1={'Apple':50,'Mango':90,'Guava':50,'Banana':60}
d1

{'Apple': 50, 'Mango': 90, 'Guava': 50, 'Banana': 60}

In [150]:
#Extracting Keys & Values
d1.keys()

dict_keys(['Apple', 'Mango', 'Guava', 'Banana'])

In [151]:
type(d1)

dict

In [152]:
d1.values()

dict_values([50, 90, 50, 60])

In [157]:
d1={'Apple':50,'Mango':90,'Guava':50,'Banana':60}

In [158]:
d1=['Apricot']=80

SyntaxError: cannot assign to literal (<ipython-input-158-61168c7c4b67>, line 1)

In [159]:
d1['Apricot']=80

In [160]:
d1

{'Apple': 50, 'Mango': 90, 'Guava': 50, 'Banana': 60, 'Apricot': 80}

In [161]:
#Changing An existing Element
d1['Apple']=100

In [162]:
d1

{'Apple': 100, 'Mango': 90, 'Guava': 50, 'Banana': 60, 'Apricot': 80}

In [164]:
#FUnctions in Dictionary
#Update one dictionary value with another

fr1={"Apple":100}
fr2={"Banana":200}
fr1.update(fr2)

In [165]:
fr1

{'Apple': 100, 'Banana': 200}

In [166]:
fr1+fr2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [168]:
#popping the dictionary elements

fr1.pop('Apple')

100

In [169]:
fr1

{'Banana': 200}

In [170]:
fr1.pop()

TypeError: pop expected at least 1 argument, got 0

In [175]:
#If statements
a=10
b=20
c=30
if a>b:
    print ("Nice")
else:
    print ("Very Nice")

Very Nice


In [174]:
if(a>b)&(a>c):
    print("a is Gretest of all")
elif(b>a)&(b>c):
    print ("b is the greatest of all")
else:
    print ("c is the greatest of all")


c is the greatest of all


In [176]:
# if statment with Tuple
tup1=("Ayesha","Umer","Zaib","Ali")
tup1

('Ayesha', 'Umer', 'Zaib', 'Ali')

In [178]:
name=input("Enter Your Name")
if name in tup1:
    print ("Conratulations you have benn selected for PAF")
else:
    print ("Sorry!,Good luck for next time")

Enter Your NameAyesha
Conratulations you have benn selected for PAF


In [179]:
type(name)

str

In [180]:
# if statement with List
l1=[1,2,3,4]
l1

[1, 2, 3, 4]

In [184]:
if l1[3]==5:
    l1[3]=4
else: 
    l1[3]=0

In [185]:
l1

[1, 2, 3, 0]

In [186]:
#if statement with Dictionary
d1={'Ayesha':60,"Umer":100,"zaib":80,"Ali":70}
d1

{'Ayesha': 90, 'Umer': 100, 'zaib': 80, 'Ali': 70}

In [197]:
name=input("Enter Your Name")
if d1[name]<80:
    print("You are failed")
else:
    print ("You are Passed")

Enter Your NameUmer
You are Passed


In [203]:
i=1
while i<=10:
    print (i)
    i=i+1

1
2
3
4
5
6
7
8
9
10


In [225]:
#While loop 
name=int(input("Enter Your Number  1 to 5 :"))
if name==1:
    i=1
    while i<=10:
        print(i)
        i=i+1
elif name==2:
    i=2
    while i<=10:
        print(i)
        i=i+1
elif name==3:
    i=3
    while i<=10:
        print(i)
        i=i+1
elif name==4:
    i=4
    while i<=10:
        print(i)
        i=i+1
elif name==5:
    i=5
    while i<=10:
        print(i)
        i=i+1
else:
   print("Enter Number only from 1 to 5 ")

Enter Your Number  1 to 5 :5
5
6
7
8
9
10


In [227]:
type(name)

int

In [248]:
# Program to Print the Table of Numbers
#LETS DO
name=int(input("Enter Your Number  2 to 5 :"))
if name==2:
    i=1
    while i<=10:
        print(name,"*",i,"=",name*i)
        i=i+1
elif name==3:
    i=1
    while i<=10:
        print(name,"*",i,"=",name*i)
        i=i+1
elif name==4:
    i=1
    while i<=10:
        print(name,"*",i,"=",name*i)
        i=i+1
elif name==5:
    i=1
    while i<=10:
        print(name,"*",i,"=",name*i)
        i=i+1
else:
   print("Enter Number only from 1 to 5 ")

Enter Your Number  2 to 5 :2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [244]:
#While Loop with List
l1=[1,2,3,4,5]
i=0
while i<len(l1):
    l1[i]=l1[i]+100
    i=i+1

In [245]:
l1

[101, 102, 103, 104, 105]

In [246]:
#For Loop with List
l1=['mango','apple','grapes']
for i in l1:
    print(i)

mango
apple
grapes


In [247]:
#Nested For Loop
l1=['orange','black']
l2=['chair','book']
for i in l1:
    for j in l2:
        print(i,j)

orange chair
orange book
black chair
black book


In [2]:
#Functions in python 
#A block of code which performs a specific task
#We need to start from the basic operation which is 'Def'
#Number 1
def hello():
    print("Ayesha Javed")
    

In [3]:
hello()

Ayesha Javed


In [4]:
#Python program to run the current statement
def add1(x):
    return x+10

In [5]:
add1(9)

19

In [6]:
add1(5)

15

In [7]:
#Program to check the number is even or odd
def even_odd(x):
    if x%2==0:
        print (x,"is the even Number")
    else:
        print (x,"is the odd Number")

In [8]:
even_odd(3)

3 is the odd Number


In [9]:
even_odd(58)

58 is the even Number


In [10]:
#Lambda Function Which is also called Anonymouse Function means it does'not have a name to be defined only in one line
g=lambda x:x*x*x
g(7)

343

In [11]:
g(8)

512

# Lambda with filter
#any sequence you want to filter the values on the basis of condition
l1={87,56,90,34,2,5,7,1}
final_l1=list(filter(lambda x:(x%2!=0) ,l1))

In [13]:
final_l1

[1, 5, 7, 87]

In [14]:
#Lambda with map
#map function used to deal with all the elements individualy
final_l2=list(map(lambda x:x*2,l1))

In [15]:
final_l2

[2, 4, 68, 10, 14, 174, 112, 180]

In [16]:
from functools import reduce 

In [17]:
sum=reduce(lambda x,y:x+y,l1)

In [18]:
sum

282

###### Here we are going to use Object_Oriented Programming in python
# Creating the class 
#1-Use class keyword 
#Class nam is always the first character is capital

class Phone:
    def make_call(self):
        print("Making Call")
    def game_play(self):
        print("Game Playing")
#2-Instantiating the Phone class objects 'P1' objects
p1=Phone()

#3-Invoking methods through objects

p1.make_call()

In [21]:
p1.game_play()

Game Playing


In [22]:
class Phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(Self):
        print("Make a Phone call")
    def play_game(self):
        print("Play a Game")
      

In [23]:
p2=Phone()

In [24]:
p2.set_color("blue")
p2.set_cost("5000")


In [25]:
p2.show_color()


'blue'

In [26]:
p2.show_cost()

'5000'

In [27]:
p2. make_call()

Make a Phone call


In [28]:
p2.play_game()

Play a Game


In [29]:
#Creating a class with constructor
#Constaructor is a special type of object to initilaize the parameters
#in the python the 'init' method act as a constructor

class Employee:
    def __init__(self,name,age,salary,gender):
        self.name=name
        self.age=age
        self.salary=salary
        self.gender=gender
    def employee_details(self):
        print("Name of employee is",self.name)
        print ("Age of employee is",self.age)
        print ("salary of employee is",self.salary)
        print ("gender of employee is",self.gender)
        
        
#Now we are going to create a class object
p3=Employee('Ayesha',23,0,'Female')

In [30]:
p3.employee_details()

Name of employee is Ayesha
Age of employee is 23
salary of employee is 0
gender of employee is Female


In [32]:

#now we ae going to create the concept of inheritance by craeting the base class and child class 
# first we need to create the super class 
class Vehicles():
    def __init__(self,milage,cost):
        self.milage=milage
        self.cost=cost
    def show_vehicles_details(self):
        print("Milage of vehicle is",self.milage)
        print("cost of vehicle is",self.cost)
        print ("I am a vehicle")

In [33]:
v1=Vehicles(300,500)

In [34]:
v1.show_vehicles_details()

Milage of vehicle is 300
cost of vehicle is 500
I am a vehicle


In [35]:
#Now creating child class
class Cari(Vehicles):
    def show_car_details(self):
        print ("This is the car")

In [36]:
c1=Cari(200,800)

In [37]:
c1.show_car_details();

This is the car


In [38]:
c1.show_vehicles_details()

Milage of vehicle is 200
cost of vehicle is 800
I am a vehicle


In [39]:
#now we ae going to create the concept of inheritance by craeting the base class and child class 
# first we need to create the super class 
class Vehicle():
    def __init__(self,milage,cost):
        self.milage=milage
        self.cost=cost
    def show_vehicles_details(self):
        print("Milage of vehicle is",self.milage)
        print("cost of vehicle is",self.cost)
        print ("I am a vehicle")

In [40]:
class jet(Vehicle):
    def __init__(self,milage,cost,tyres,hp):
        super().__init__(milage,cost)
        self.tyres=tyres
        self.hp=hp
    def show_jet_details(self):
        print("Number of tyres",self.tyres)
        print("Hp of jet",self.hp)
        print("I am a car")

In [41]:
c2=jet(300,200,400,100)

In [42]:
c2.show_vehicles_details()

Milage of vehicle is 300
cost of vehicle is 200
I am a vehicle


In [43]:
c2.show_jet_details()

Number of tyres 400
Hp of jet 100
I am a car


In [44]:
#here we are using multiple inhertance concept in python 
#Where Two paraents Inherited by One child
# IT IS DONE BY USING CHILD CLASS INSTANCE

class Parent1():
    def assign_string_one(self,str1):
        self.str1=str1
    def show_string_one(self):
        return self.str1

In [45]:
#Parent class 2
class Parent2():
    def assign_string_two(self,str2):
        self.str2=str2
    def show_string_two(self):
        return self.str2

In [46]:
#child class
class Derived(Parent1,Parent2):
    def assign_string_three(self,str3):
        self.str3=str3
    def show_string_three(self):
        return self.str3

In [47]:
#Instantiating Objects of child class
d10 = Derived()
d10.assign_string_one("one")
d10.assign_string_two("two")
d10.assign_string_three("three")

In [48]:
d10.show_string_one()

'one'

In [49]:
d10.show_string_two()

'two'

In [50]:
d10.show_string_three()

'three'

In [60]:
#Multi-level Inheritance
#Parent class
class Parent():
    def assign_name(self,name):
        self.name=name
    def show_name(self):
        return self.name
    

In [61]:
#Child Class
class Child(Parent):
    def assign_age(self,age):
        self.age=age
    def show_age(self):
        return self.age

In [63]:
#Grand Child
class Grandchild(Child):
    def assign_gender(self,gender):
        self.gender=gender
    def show_gender(self):
        return self.gender

In [64]:
gc=Grandchild()

In [65]:
gc.assign_gender("Female")

In [66]:
gc.assign_age(23)

In [67]:
gc.assign_name("Ayesha")

In [68]:
gc.show_name()

'Ayesha'

In [69]:
gc.show_age()

23

In [70]:
gc.show_gender()

'Female'

In [ ]:
#Now the end of the basics of python in jupyter console application 
#We will learn
#Quiz


### PYTHON MACHINE LEARNING TUTORAIL
#Libraries
python library is a collection of fuction and methods that allows you to perform many actions without writing your code 

there are different libraries  such as 
1-Numpy
2-Matplotlib
3-Pandas
etc..

Purpose is to provide inbuilt fuctions to make work easier 

Python Numpy:-
    Numpy stands Numerical python and is the core library for numeric and scientific computing,it consists of multi-dimensional array objects and a collection of routines for processing these arrays
    
    Numpy Arrays:-
    1-Single-dimensional array
    2-Multi-dimensional array
    

In [5]:
#1-single dimensional array

import numpy as np

n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [9]:
#2-Multi-dimensional array
import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2
    

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [10]:
type(n1)

numpy.ndarray

In [11]:
type(n2)

numpy.ndarray

In [13]:
#Initializing Numpy Array with zeros

import numpy as np
n1=np.zeros((1,2))
n2=np.zeros((5,10))
n1
n2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
#Initializing Numpy array with same number

import numpy as np

n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [15]:
n1=np.full((2,2),10,20)
n1

TypeError: Cannot interpret '20' as a data type

In [16]:
#Initializing Numpy array witin a range the purpose is to initialize ar make a numpy array within perticular range
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
import numpy as np
n2=np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
#Initializing Numpy array with random numbers every time the numbers are changed for that we need to use random methos of numpy library and use submethod of random method which is randint
#the parameters of the randint method is the (lower_limit,upper_limit,range_number)
import numpy as np
n1=np.random.randint(10,50,6)
n1

array([11, 43, 24, 44, 17, 41])

In [23]:
#How to change the shape of Numpy array
#Simply create the numpy array and then call the method of shape
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#Now to check the shape of numpy array means (row,column)
n1.shape

(2, 3)

In [29]:
#if you want to change the shape of the array then simply you use,change of array means the cordinates of row and column is changed
n1.shape=(3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# joining Numpy array
# vstack(Vertically stack joining)
# hstack(horizontally stack joining)
# column_stack(coulumn wise stack joining)

import numpy as np
n1=np.array([1,2])
n2=np.array([3,4])
# vstack
np.vstack((n1,n2))



array([[1, 2],
       [3, 4]])

In [31]:
#hstack
np.hstack((n1,n2))

array([1, 2, 3, 4])

In [32]:
#column_stack
np.column_stack((n1,n2))

array([[1, 3],
       [2, 4]])

In [33]:
# Numpy difference and Intersection between two Arrays
np.intersect1d((n1,n2))

TypeError: _intersect1d_dispatcher() missing 1 required positional argument: 'ar2'

In [53]:
import numpy as np
n1=np.array([1,2])
n2=np.array([3,4])
result=np.intersect1d(n1,n2)
if result:
     print("No record")


else:
    result


<ipython-input-53-5b6e6487ebf8>:5: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if result:


array([], dtype=int32)

In [54]:
np.setdiff1d(n1,n2)

array([1, 2])

In [55]:
np.setdiff1d(n2,n1)

array([3, 4])

In [61]:
#Addition of Numpy Array 
#All 
#corresponding 
#single 
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
#All
np.sum((n1,n2))
#also individual


100

In [62]:
np.sum((n1))

30

In [63]:
np.sum(n1)

30

In [57]:
#corresponding give axis value of the axis =0 means to add corresponding values column wise adition
np.sum([n1,n2],axis=0)


array([40, 60])

In [64]:
#addition of single numpy array the axis =1
np.sum([n1,n2],axis=1)

array([30, 70])

In [65]:
#Numpy Array Mathematics DMAS

import numpy as np
n1=np.array([10,30])
## Basic Addition
n1+2

array([12, 32])

In [66]:
# Basic Subtraction
n1-3

array([ 7, 27])

In [67]:
# Basic Multiplication
n1*2

array([20, 60])

In [68]:
# Basic Division
n1/2

array([ 5., 15.])

In [69]:
#Numpy Math Functions
#Mean
import numpy as np
n1=np.array([10,20,30])
np.mean(n1)

20.0

In [70]:
np.std(n1)

8.16496580927726

In [71]:
np.median(n1)

20.0

In [72]:
#saving and Loading Numpy Array 
import numpy as np
n1=np.array([10,20,30])
np.save('my save',n1)

In [73]:
#loading Numpy array
n2=np.load('my save.npy')

In [74]:
n2

array([10, 20, 30])

# PANDAS Library 
#Pandas stands for Panel data and is the core library for data manupulation 
#it consists of single and multi-dimensional date structures for data manipulation

#series  object
#series objects is one dimensional labeled array 
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

In [6]:
#changing the inde value
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
#series objects from dictionary
#you can also create a series objects from a dictionary
import pandas as pd
pd.Series({'a':10,'b':20,'c':30})



a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series({'a':10,'b':20,'c':30},index=['ayesha','b','c','a','b'])

ayesha     NaN
b         20.0
c         30.0
a         10.0
b         20.0
dtype: float64

In [11]:
#Extracting a single element
s1=pd.Series([1,2,3,4,5,9,7,5,3,7,2,0])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
s1[3]

4

In [13]:
s1[:5]#extrcating a sequence of elements

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [25]:
s1=pd.Series([1,2,3,4,5,9,7,5,3,7,2,0])
s1[-5:]

7     5
8     3
9     7
10    2
11    0
dtype: int64

In [26]:
#Adding Scalar value to scalar element
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([3,4,5,6,7])
s1,s2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
 0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64)

In [32]:
s1=s1+5
s1

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [33]:
s2=s2+2
s2

0     7
1     8
2     9
3    10
4    11
dtype: int64

In [34]:
s1,s2

(0    11
 1    12
 2    13
 3    14
 4    15
 dtype: int64,
 0     7
 1     8
 2     9
 3    10
 4    11
 dtype: int64)

In [35]:
#addition 
sadd=s1+s2
sadd

0    18
1    20
2    22
3    24
4    26
dtype: int64

In [36]:
ssub=s1-s2
ssub

0    4
1    4
2    4
3    4
4    4
dtype: int64

In [2]:
#Pandas is used to craete 2 dimensional labeleld table or data
#pandas DataFrame is used to create 2-d labeled data structures ,comprises of rows and columns
#create dataframe with the help of dictionary

import pandas as pd
df1=pd.DataFrame({"Name":['Ayesha','Zaib','Umer','Ali'],"Marks":[100,98,99,97]})
df1

Name  Marks
0  Ayesha    100
1    Zaib     98
2    Umer     99
3     Ali     97

In [5]:
#DataFrame in-built Fuction
#shape(),#head(),#tail(),describe()
#we need to use Iris dataset if we want to use the in-built Functions
import pandas as pd
iris=pd.read_csv('iris.csv')
iris.head()

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [6]:
import pandas as pd
df1=pd.DataFrame({"Name":['Ayesha','Zaib','Umer','Ali','bob','petal','kio'],"Marks":[100,98,99,97,99,76,46]})
df1.head()

Name  Marks
0  Ayesha    100
1    Zaib     98
2    Umer     99
3     Ali     97
4     bob     99

In [7]:
df1.tail()

Name  Marks
2   Umer     99
3    Ali     97
4    bob     99
5  petal     76
6    kio     46

In [9]:
df1.shape

(7, 2)

In [10]:
df1.describe()

Marks
count    7.000000
mean    87.857143
std     20.309510
min     46.000000
25%     86.500000
50%     98.000000
75%     99.000000
max    100.000000

In [11]:
#How to extract the individual rows of DataFrame ,use 
#1-iloc() method
#2-loc()  method

#iloc() method

df1.iloc[0:3,0:1]

Name
0  Ayesha
1    Zaib
2    Umer

In [12]:
df1.loc[0:3,("Name","Marks")]

Name  Marks
0  Ayesha    100
1    Zaib     98
2    Umer     99
3     Ali     97

In [13]:
#Dropping Value from dataframe
#to drop perticular column axis=1(column)
#to drop perticular row    axis=0(rows)
df1.drop("Marks",axis=1)

Name
0  Ayesha
1    Zaib
2    Umer
3     Ali
4     bob
5   petal
6     kio

In [14]:
df1

Name  Marks
0  Ayesha    100
1    Zaib     98
2    Umer     99
3     Ali     97
4     bob     99
5   petal     76
6     kio     46

In [15]:
df1.drop([2],axis=0)

Name  Marks
0  Ayesha    100
1    Zaib     98
3     Ali     97
4     bob     99
5   petal     76
6     kio     46

In [16]:
#Pandas Functions 
#mean()
df1.mean()

Marks    87.857143
dtype: float64

In [17]:
#min()
df1.min()

Name     Ali
Marks     46
dtype: object

In [18]:
#max()
df1.max()

Name     petal
Marks      100
dtype: object

In [19]:
#median()
df1.median()

Marks    98.0
dtype: float64

In [22]:
#apply method is used to work on different column perticular which are mentioned
def half(s):
    return s*0.5
    



In [23]:
df1[["Marks"]].apply(half)

Marks
0   50.0
1   49.0
2   49.5
3   48.5
4   49.5
5   38.0
6   23.0

In [24]:
#value counts#categorical columns
df1['Marks'].value_counts()

99     2
46     1
76     1
100    1
98     1
97     1
Name: Marks, dtype: int64

In [25]:
df1.sort_values(by="Marks")

Name  Marks
6     kio     46
5   petal     76
3     Ali     97
1    Zaib     98
2    Umer     99
4     bob     99
0  Ayesha    100